### ISSUE TITLE
[LOC] "Windows こんにちは" needs to be replaced with "Windows Hello"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/IntuneDocs.ja-jp#43]
https://docs.microsoft.com/ja-jp/intune/device-restrictions-windows-10

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e0658178-6f7d-6d02-9805-1b23491d35ac
* Version Independent ID: 2b95f982-2bbf-4968-bf65-9c3abfd98c3f
* Content: [Microsoft Intune での Windows 10 用のデバイスの制限設定 - Azure](https://docs.microsoft.com/ja-jp/intune/device-restrictions-windows-10)
* Content Source: [intune/device-restrictions-windows-10.md](https://github.com/MicrosoftDocs/IntuneDocs.ja-jp/blob/live/intune/device-restrictions-windows-10.md)
* Service: **microsoft-intune**
* Product: ****
* Technology: ****
* GitHub Login: @MandiOhlinger
* Microsoft Alias: **mandia**

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/intune/device-restrictions-windows-10

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
